### ISSUE TITLE
How to get a cloud managed minio storage server

### ISSUE THREAD

**Issue by mickeymond** [alireza12prom/multer-minio#3]
@alireza12prom I came here to contribute to this repo to facilitate my teaching of the MERN stack.
During the facilitation, I had to run a **minio server** on my local workstation using docker and then get the students to access it over the local network.
But if they now want to publish their app, I need a cloud-managed minio service.
Preferably, with a free-to-start subscription.
Is there something like that?

**Comment by namatery** [comment]
Hi @mickeymond,
I googled but all the cloud providers I saw had no free-to-start subscription I'm afraid.
Where do your students want to publish their apps? I mean if you have a server, you can easily run the Minio and then publish the port of that to be accessible from outside.

**Comment by mickeymond** [comment]
@alireza12prom Thank you very much.
I found https://play.min.io which can be used for demonstration and learning purposes.
I think this issue can be closed.

**Comment by namatery** [comment]
@mickeymond That's great, good luck!
